// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_restaurants from "./routes/api/restaurants.ts";
import * as $api_stats from "./routes/api/stats.ts";
import * as $api_votes from "./routes/api/votes.ts";
import * as $index from "./routes/index.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/restaurants.ts": $api_restaurants,
    "./routes/api/stats.ts": $api_stats,
    "./routes/api/votes.ts": $api_votes,
    "./routes/index.tsx": $index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
